// Form Rule Pack - Strength Exercises v1.0
// Used by AI Coach for real-time form evaluation

export const strengthRulePack = {
  pack_id: 'strength_v1',
  version: '1.0.0',
  author: 'Motion',
  description: 'Form rules for common strength exercises',
  
  models: {
    default: 'movenet_lightning',
    barbell_back_squat: 'blazepose_full',
    deadlift: 'blazepose_full',
    push_up: 'movenet_lightning',
    bench_press: 'blazepose_full',
  },

  camera_hints: {
    barbell_back_squat: { view: 'side', feet_fully_visible: true },
    deadlift: { view: 'side', feet_fully_visible: true },
    bench_press: { view: 'side' },
    push_up: { view: 'side' },
    overhead_press: { view: 'side' },
    barbell_row: { view: 'side' },
  },

  exercises: [
    {
      id: 'barbell_back_squat',
      name: 'Barbell Back Squat',
      phases: ['descent', 'bottom', 'ascent', 'lockout'],
      rules: [
        {
          id: 'depth_parallel',
          when_phase: 'bottom',
          measure: 'angle',
          points: ['hip', 'knee', 'ankle'],
          target: { op: '<=', value_deg: 90 },
          tolerance_deg: 10,
          penalty: 8,
          coaching: 'Sit slightly deeper until thighs are parallel.',
          heatmap: { joint: 'hip', radius: 60, color: 'warn' },
        },
        {
          id: 'knee_valgus',
          when_phase: 'descent|ascent',
          measure: 'distance_to_line',
          from: 'hip',
          to: 'ankle',
          point: 'knee',
          target: { op: '>=', value_px: 0 },
          tolerance_px: 8,
          penalty: 10,
          coaching: 'Push knees out over toes.',
          heatmap: { joint: 'knee', radius: 50, color: 'bad' },
        },
        {
          id: 'lumbar_flexion',
          when_phase: 'descent|ascent',
          measure: 'angle_delta',
          points: ['shoulder', 'hip', 'knee'],
          baseline: 'lockout',
          target: { op: '<=', value_deg: 8 },
          penalty: 12,
          coaching: 'Brace your core; keep chest up.',
          heatmap: { segment: 'spine', radius: 80, color: 'bad' },
        },
      ],
    },
    {
      id: 'deadlift',
      name: 'Conventional Deadlift',
      phases: ['setup', 'pull', 'lockout', 'eccentric'],
      rules: [
        {
          id: 'bar_path_over_midfoot',
          when_phase: 'pull',
          measure: 'horizontal_offset',
          point: 'wrist',
          ref: 'ankle',
          target: { op: '<=', value_px: 20 },
          penalty: 8,
          coaching: 'Keep bar close to shins.',
          heatmap: { segment: 'shin', radius: 55, color: 'warn' },
        },
        {
          id: 'back_rounding',
          when_phase: 'pull|eccentric',
          measure: 'angle_delta',
          points: ['shoulder', 'hip', 'knee'],
          baseline: 'setup',
          target: { op: '<=', value_deg: 8 },
          penalty: 12,
          coaching: 'Neutral spine—pull chest through.',
          heatmap: { segment: 'spine', radius: 70, color: 'bad' },
        },
        {
          id: 'lockout_hip_extension',
          when_phase: 'lockout',
          measure: 'angle',
          points: ['shoulder', 'hip', 'knee'],
          target: { op: '>=', value_deg: 170 },
          tolerance_deg: 5,
          penalty: 5,
          coaching: 'Squeeze glutes at lockout.',
          heatmap: { joint: 'hip', radius: 50, color: 'ok' },
        },
      ],
    },
    {
      id: 'push_up',
      name: 'Push-Up',
      phases: ['down', 'bottom', 'up', 'lockout'],
      rules: [
        {
          id: 'elbow_depth',
          when_phase: 'bottom',
          measure: 'angle',
          points: ['shoulder', 'elbow', 'wrist'],
          target: { op: '<=', value_deg: 90 },
          tolerance_deg: 10,
          penalty: 6,
          coaching: 'Lower until elbows reach 90°.',
          heatmap: { joint: 'elbow', radius: 40, color: 'warn' },
        },
        {
          id: 'hip_sag',
          when_phase: 'down|up',
          measure: 'angle_delta',
          points: ['shoulder', 'hip', 'ankle'],
          baseline: 'lockout',
          target: { op: '<=', value_deg: 6 },
          penalty: 8,
          coaching: 'Squeeze glutes; keep hips level.',
          heatmap: { joint: 'hip', radius: 50, color: 'bad' },
        },
        {
          id: 'elbow_flare',
          when_phase: 'down|bottom|up',
          measure: 'angle',
          points: ['shoulder', 'elbow', 'hip'],
          target: { op: '<=', value_deg: 45 },
          tolerance_deg: 10,
          penalty: 6,
          coaching: 'Tuck elbows closer to body.',
          heatmap: { joint: 'elbow', radius: 45, color: 'warn' },
        },
      ],
    },
    {
      id: 'bench_press',
      name: 'Bench Press',
      phases: ['unrack', 'descent', 'bottom', 'press', 'lockout'],
      rules: [
        {
          id: 'touch_point',
          when_phase: 'bottom',
          measure: 'vertical_position',
          point: 'wrist',
          ref: 'shoulder',
          target: { op: '<=', value_ratio: 0.6 },
          penalty: 6,
          coaching: 'Touch bar to lower chest/sternum.',
          heatmap: { segment: 'chest', radius: 60, color: 'warn' },
        },
        {
          id: 'arch_maintained',
          when_phase: 'descent|press',
          measure: 'angle_delta',
          points: ['shoulder', 'hip', 'knee'],
          baseline: 'unrack',
          target: { op: '<=', value_deg: 5 },
          penalty: 4,
          coaching: 'Maintain back arch throughout.',
          heatmap: { segment: 'spine', radius: 50, color: 'warn' },
        },
      ],
    },
    {
      id: 'overhead_press',
      name: 'Overhead Press',
      phases: ['setup', 'press', 'lockout', 'descent'],
      rules: [
        {
          id: 'bar_path',
          when_phase: 'press|lockout',
          measure: 'horizontal_offset',
          point: 'wrist',
          ref: 'shoulder',
          target: { op: '<=', value_px: 15 },
          penalty: 7,
          coaching: 'Press bar straight up over shoulders.',
          heatmap: { joint: 'shoulder', radius: 50, color: 'warn' },
        },
        {
          id: 'lean_back',
          when_phase: 'press',
          measure: 'angle',
          points: ['shoulder', 'hip', 'ankle'],
          target: { op: '>=', value_deg: 175 },
          tolerance_deg: 5,
          penalty: 8,
          coaching: 'Stay upright; avoid excessive lean.',
          heatmap: { segment: 'spine', radius: 60, color: 'bad' },
        },
      ],
    },
  ],
};

export type RulePack = typeof strengthRulePack;
export type Exercise = typeof strengthRulePack.exercises[number];
export type Rule = Exercise['rules'][number];
